### UserService 테스트
GET http://localhost:8081/users/1
Accept: application/json

### PostService 테스트 (정상 호출)
GET http://localhost:8080/posts/1
Accept: application/json

### PostService 테스트 (UserService 중단 시)
# UserService 프로세스를 중단한 후 테스트
GET http://localhost:8080/posts/1
Accept: application/json

### Docker 환경 테스트
# Docker 컨테이너 내부에서의 통신 테스트
GET http://postservice:8080/posts/1
Accept: application/json
